; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.maximum_size = 16777216
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.filesystem = spiffs
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 1
lib_compat_mode = strict
board_build.extra_flags = -DBOARD_HAS_PSRAM
	-DRTC_DISABLE_ROM_LOG=0
	#-DCORE_DEBUG_LEVEL=5
lib_deps = 
	https://github.com/RobTillaart/RS485.git
	tzapu/WiFiManager @ ^2.0.16
	https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library.git
	https://github.com/RobTillaart/PCF8574.git
	esp32async/ESPAsyncWebServer@^3.7.10
	bblanchon/ArduinoJson@^7.4.2
	https://github.com/emelianov/modbus-esp8266.git
	https://github.com/adafruit/Adafruit_NeoPixel.git
	https://github.com/adafruit/Adafruit_ADS1X15.git
	forntoh/LcdMenu@^5.12.1
	marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
	https://github.com/ayushsharma82/ElegantOTA.git
	adafruit/Adafruit SSD1306 @ ^2.5.16
	https://github.com/adafruit/Adafruit-GFX-Library.git
	adafruit/Adafruit SH110X @ ^2.1.14
	olikraus/U8g2 @ ^2.36.15
	#https://github.com/birdtechstep/modbus-esp.git

[env:wemos_d1_mini32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.03/platform-espressif32.zip
board = wemos_d1_mini32
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/RobTillaart/RS485.git
	networking-for-arduino/EthernetESP32@^1.0.2
	https://github.com/tzapu/WiFiManager.git
	https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library.git
	https://github.com/RobTillaart/PCF8574.git
